#!/bin/sh -e
#
# 2016 Carlos Ortigoza (carlos.ortigoza at ungleich.ch)
# 2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "${__global:?}/explorer/os")
keyboard_type=$(cat "${__object:?}/parameter/type")

case ${os}
in
    (centos|oraclelinux)
        # NOTE: This is a hack to differentiate Red Hat Linux from
        # RHEL. Red Hat Linux >= 7 does not have os-release and will
        # thus fall back to /etc/sysconfig/i18n.
        # shellcheck source=/dev/null
        version_id=$(. "${__global:?}/explorer/os_release" && echo "${VERSION_ID:-0}")
        if test "${version_id%%[!0-9]*}" -ge 7
        then
            __file /etc/vconsole.conf --state exists \
                --owner 0 --group 0 --mode 0644
        else
            __file /etc/sysconfig/keyboard --state exists \
                --owner 0 --group 0 --mode 0644

            require=__file/etc/sysconfig/keyboard \
            __key_value /etc/sysconfig/keyboard:KEYTABLE \
                --file /etc/sysconfig/keyboard \
                --delimiter '=' --exact_delimiter \
                --key 'KEYTABLE' \
                --value "\"${keyboard_type}\""

            require=__file/etc/sysconfig/keyboard \
            __key_value /etc/sysconfig/keyboard:LAYOUT \
                --file /etc/sysconfig/keyboard \
                --delimiter '=' --exact_delimiter \
                --key 'LAYOUT' \
                --value "\"${keyboard_type}\""
        fi
        ;;
    (crux)
        __key_value /etc/rc.conf:KEYMAP \
            --file /etc/rc.conf \
            --delimiter '=' --exact_delimiter \
            --key KEYMAP \
            --value "${keyboard_type}"
        ;;
    (*)
        echo "Your operating system (${os}) is currently not supported by this type (${__type##*/})." >&2
        echo "Please contribute an implementation for it if you can." >&2
        exit 1
        ;;
esac
