#!/bin/sh -e
#
# 2023-2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

shquot() {
	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
	$*
	EOF
}

confdir=$(cat "${__object:?}/parameter/confdir")

read -r state_is <"${__object:?}/explorer/state"
read -r state_should <"${__object:?}/parameter/state"

test "${state_should}" != "${state_is}" || exit 0

case ${state_should}
in
	(present)
		if test -f "${__object:?}/parameter/mail"
		then
			email=$(cat "${__object:?}/parameter/mail")
		elif test -f "${__object:?}/parameter/admin-mail"
		then
			# fall back to deprecated --admin-mail
			email=$(cat "${__object:?}/parameter/admin-mail")
		fi

		printf 'uacme --confdir %s --yes new%s\n' \
			"$(shquot "${confdir:?}")" \
			"${email:+ $(shquot "${mail-}")}"
		;;
	(absent)
		# deletion of --confdir is handled in manifest

		if test -f "${__object:?}/parameter/deactivate-if-absent"
		then
			printf 'uacme --confdir %s deactivate\n' \
				"$(shquot "${confdir:?}")" \
		fi
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
