#!/bin/sh -e
#
# 2023-2025 Dennis Camera (dennis.camera at riiengineering.ch)
#
# This file is part of skonfig-extra.
#
# skonfig-extra is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# skonfig-extra is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with skonfig-extra. If not, see <http://www.gnu.org/licenses/>.
#

confdir=$(cat "${__object:?}/parameter/confdir")
state_should=$(cat "${__object:?}/parameter/state")

__package uacme

case ${state_should}
in
	(present)
		case ${confdir}
		in
			(/etc/ssl/uacme)
				# default
				__directory /etc/ssl \
					--owner 0 --group 0 --mode 0755

				require=__directory/etc/ssl
				export require
				;;
		esac

		__directory "${confdir:?}" \
			--owner 0 --group 0 --mode 0755

		require="__directory${confdir:?}" \
		__directory "${confdir:?}/private" \
			--owner 0 --group 0 --mode 0700
		;;
	(absent)
		# NOTE: require __object_name to allow for clean ups (deactivating
		#       the account) in code-remote before deleting the --confdir.
		require=${__object_name:?} \
		__directory "${confdir:?}" \
			--state absent
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
